name: weather_band
description: A new way to predict the weather to your greatest day.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.1.0
  dio: ^5.1.2
  flutter_svg: ^1.0.3
  oktoast: ^3.2.0
  flutter_modular: ^5.0.3
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/